### ISSUE TITLE
Change language in Wine

### ISSUE THREAD

**Issue by Massouille78** [PTKickass/GenerationsConfigTool_Rewrite#5]
Good morning,

Thank you for this configurator, everything works correctly on Windows 10.

But, when I use wine on batocera, I cannot change the language via the configurator. When I click on the icon next to the "admin rights" language selection, the software restarts and nothing happens.

Where is the system language stored in LOCAL_MACHINE located? I would like to change my language to French.

Which file is modified after this language change?

What modif Reg is executing in language ?

Thank you in advance for your answer

**Comment by RagdollClash** [comment]
You can change the language through Steam in the game's properties.

![2024-04-08_13-41-18_steamwebhelper](https://github.com/PTKay/GenerationsConfigTool_Rewrite/assets/15317421/c97ae3bc-4a4d-4702-8e83-d04f2259a35e)

**Comment by PTKay** [comment]
As mentioned, this can be changed through the Steam launcher. However, you can see how the Registry configuration is edited in this file: https://github.com/PTKay/GenerationsConfigTool_Rewrite/blob/main/GensConfigTool/Model/Configurations/RegistryConfiguration.cs

To summarise, settings are located in `LocalMachine\SOFTWARE\Sega\Sonic Generations`. Language is defined by the `locale` key.

As a final note, I do not officially support Linux or Wine in this tool, so I'm unable to solve issues related to those kinds of setups. Thank you for understanding.
